id: cis_55__class_1_introduction_to_cybersecurity
name: 'CIS 55 - Class 1: Introduction to Cybersecurity'
questions:
- answer: A
  options:
  - A) Confidentiality, Integrity, Availability
  - B) Control, Identification, Authentication
  - C) Compliance, Investigation, Access
  - D) Cybersecurity, Intelligence, Analysis
  question: What are the three core principles of the CIA triad in cybersecurity?
- answer: C
  options:
  - A) Exploitation
  - B) Scanning
  - C) Reconnaissance
  - D) Reporting
  question: Which phase of penetration testing involves gathering as much information
    about the target as possible?
- answer: B
  options:
  - A) Metasploit
  - B) Nessus
  - C) Wireshark
  - D) John the Ripper
  question: Which tool is commonly used for network and web application vulnerability
    scanning?
- answer: C
  options:
  - A) Internal Penetration Testing
  - B) Targeted Testing
  - C) Blind Penetration Testing
  - D) External Penetration Testing
  question: What type of penetration testing simulates an attacker with no prior knowledge
    of the target?
- answer: D
  options:
  - A) Social Engineering
  - B) Brute Force Attacks
  - C) Privileged Access Misuse
  - D) Intrusion Detection Systems
  question: Which of the following is NOT a common attack vector?
