services:
  app:
    build: .
    ports:
      - $PORT:$PORT
    environment:
      PORT: $PORT
      MAIL_PASSWORD: $MAIL_PASSWORD
      SECRET_KEY: $SECRET_KEY
      DATABASE_NAME: $DATABASE_NAME  # Use Docker volume path for persistence
    volumes:
      - app-data:/app/data  # Mount the volume for database persistence
    tty: true
    stdin_open: true

volumes:
  app-data:

