version: '3'
services:
  app:
    build: .
    ports:
      - $PORT:$PORT
    depends_on:
      - migrate
    environment:
      PORT: $PORT
      DATABASE_NAME: "/app/data/app.db"  # Use Docker volume path for persistence
    volumes:
      - app-data:/app/data  # Mount the volume for database persistence
    tty: true
    stdin_open: true

  migrate:
    build: .
    environment:
      DATABASE_NAME: "/app/data/app.db"
    volumes:
      - app-data:/app/data
    command: ["python","migrations.py"]

volumes:
  app-data:

